export function getAssetPath(itemType : string): string {
    const assetMap = new Map([
        ["BroomCabinet_01", "/png/Broom Cabinet/cabinet 1.png"],
        ["BroomCabinet_02", "/png/Broom Cabinet/cabinet 2.png"],
        ["BroomCabinet_03", "/png/Broom Cabinet/cabinet 3.png"],
        ["BroomCabinet_04", "/png/Broom Cabinet/cabinet 4.png"],
        ["BroomCabinet_05", "/png/Broom Cabinet/cabinet 5.png"],
        ["BroomCabinet_06", "/png/Broom Cabinet/cabinet 6.png"],
        ["BroomCabinet_07", "/png/Broom Cabinet/cabinet 7.png"],
        ["BroomCabinet_08", "/png/Broom Cabinet/cabinet 8.png"],
        ["BroomCabinet_09", "/png/Broom Cabinet/cabinet 9.png"],
        ["BroomCabinet_10", "/png/Broom Cabinet/cabinet 10.png"],
        ["Tree_06", "/png/Tree/tree 1.png"],
        ["Vase_08", "/png/Vase/vase 1.png"],
        ["Vase_11", "/png/Vase/vase 2.png"],
        ["Sewingkit_07", "/png/Sewing/sewing.png"],
        ["ProducerBoosterActivated_01", "/png/Booster/boost 1.png"],
        ["TimeSkipBooster_01", "/png/Booster/boost 4.png"],
        ["GardenToolBarrel_02", "/png/Garden Tool/tool 1.png"],
        ["GardenToolBarrel_07", "/png/Garden Tool/tool 2.png"],
        ["GardenToolBarrel_06", "/png/Garden Tool/tool 3.png"],
        ["GardenToolBarrel_04", "/png/Garden Tool/tool 4.png"],
        ["GardenToolBarrel_08", "/png/Garden Tool/tool 5.png"],
        ["GardenToolBarrel_11", "/png/Garden Tool/tool 6.png"],
        ["MaintenanceMaterials_07", "/png/Maintainance material/material 1.png"],
        ["Drawer_03", "/png/Drawer/drawer 1.png"],
        ["Drawer_08", "/png/Drawer/drawer 2.png"],
        ["Drawer_07", "/png/Drawer/drawer 3.png"],
        ["Drawer_06", "/png/Drawer/drawer 4.png"],
        ["FancyBlueChest_01", "/png/Chest/blue.png"],
        ["BrownChest_01", "/png/Chest/brown.png"],
        ["Thread_11", "/png/Sewing/thread.png"],
        ["LDE_HolidayCarols2023_EntranceEnter_01", "/png/Holiday/entrance.png"],
        ["PiggyBank_02", "/png/Piggy Bank/bank.png"],
        ["GoldRoot_08", "/png/Gold/root.png"],
        ["Flowerpot_10", "/png/Flower Pot/flower 1.png"],
        ["LevelDownBoosterScissors_01", "/png/Scissors/scissors.png"],
        ["ConservatorySeedlingKitEmpty_01", "/png/Seedling kit/kit.png"],
        ["GardenBench_08", "/png/Bench/bench.png"],
        ["TimeSkipBoosterSingle_01", "/png/Booster/time skip.png"],
        ["MaintenanceTools_08", "/png/Maintainance tool/tool 1.png"],
        ["MaintenanceTools_09", "/png/Maintainance tool/tool 2.png"],
        ["MaintenanceTools_10", "/png/Maintainance tool/tool 3.png"],
        ["MaintenanceTools_11", "/png/Maintainance tool/tool 4.png"], 
        ["Toolbox_03", "/png/Toolbox/box 1.png"],
        ["Toolbox_07", "/png/Toolbox/box 2.png"],
        ["Toolbox_09", "/png/Toolbox/box 3.png"],
        ["Toolbox_05", "/png/Toolbox/box 4.png"],
        ["ToyCar_05", "/png/Toy car/car 1.png"],
        ["ToyCar_07", "/png/Toy car/car 2.png"],
        ["ToyCar_10", "/png/Toy car/car 3.png"],
        ["ToyCar_06", "/png/Toy car/car 4.png"],
        ["PlantedBush_08", "/png/Planted Bush/bush 1.png"],
        ["PlantedBush_09", "/png/Planted Bush/bush 2.png"],
        ["PlantedBush_07", "/png/Planted Bush/bush 3.png"],
        ["PlantedBush_05", "/png/Planted Bush/bush 4.png"],
        ["Energy_02", "/png/Energy/energy 1.png"],
        ["Energy_05", "/png/Energy/energy 2.png"],
        ["Workbench_05", "/png/Workbench/workbench 1.png"],
        ["Workbench_07", "/png/Workbench/workbench 2.png"],
      ])
      const computedURL = new URL(assetMap.get(itemType)! || "/not-found.png", import.meta.url).href
    return 'url(' + computedURL + ')'
}