export function getAssetPath(itemType : string): string {
    const assetMap = new Map([
        ["BroomCabinet_01", "assets/png/Broom Cabinet/cabinet 1.png"],
        ["BroomCabinet_02", "assets/png/Broom Cabinet/cabinet 2.png"],
        ["BroomCabinet_03", "assets/png/Broom Cabinet/cabinet 3.png"],
        ["BroomCabinet_04", "assets/png/Broom Cabinet/cabinet 4.png"],
        ["BroomCabinet_05", "assets/png/Broom Cabinet/cabinet 5.png"],
        ["BroomCabinet_06", "assets/png/Broom Cabinet/cabinet 6.png"],
        ["BroomCabinet_07", "assets/png/Broom Cabinet/cabinet 7.png"],
        ["BroomCabinet_08", "assets/png/Broom Cabinet/cabinet 8.png"],
        ["BroomCabinet_09", "assets/png/Broom Cabinet/cabinet 9.png"],
        ["BroomCabinet_10", "assets/png/Broom Cabinet/cabinet 10.png"],
        ["Tree_06", "assets/png/Tree/tree 1.png"],
        ["Vase_08", "assets/png/Vase/vase 1.png"],
        ["Vase_11", "assets/png/Vase/vase 2.png"],
        ["Sewingkit_07", "assets/png/Sewing/sewing.png"],
        ["ProducerBoosterActivated_01", "assets/png/Booster/boost 1.png"],
        ["TimeSkipBooster_01", "assets/png/Booster/boost 4.png"],
        ["GardenToolBarrel_02", "assets/png/Garden Tool/tool 1.png"],
        ["GardenToolBarrel_07", "assets/png/Garden Tool/tool 2.png"],
        ["GardenToolBarrel_06", "assets/png/Garden Tool/tool 3.png"],
        ["GardenToolBarrel_04", "assets/png/Garden Tool/tool 4.png"],
        ["GardenToolBarrel_08", "assets/png/Garden Tool/tool 5.png"],
        ["GardenToolBarrel_11", "assets/png/Garden Tool/tool 6.png"],
        ["MaintenanceMaterials_07", "assets/png/Maintainance material/material 1.png"],
        ["Drawer_03", "assets/png/Drawer/drawer 1.png"],
        ["Drawer_08", "assets/png/Drawer/drawer 2.png"],
        ["Drawer_07", "assets/png/Drawer/drawer 3.png"],
        ["Drawer_06", "assets/png/Drawer/drawer 4.png"],
        ["FancyBlueChest_01", "assets/png/Chest/blue.png"],
        ["BrownChest_01", "assets/png/Chest/brown.png"],
        ["Thread_11", "assets/png/Sewing/thread.png"],
        ["LDE_HolidayCarols2023_EntranceEnter_01", "assets/png/Holiday/entrance.png"],
        ["PiggyBank_02", "assets/png/Piggy Bank/bank.png"],
        ["GoldRoot_08", "assets/png/Gold/root.png"],
        ["Flowerpot_10", "assets/png/Flower Pot/flower 1.png"],
        ["LevelDownBoosterScissors_01", "assets/png/Scissors/scissors.png"],
        ["ConservatorySeedlingKitEmpty_01", "assets/png/Seedling kit/kit.png"],
        ["GardenBench_08", "assets/png/Bench/bench.png"],
        ["TimeSkipBoosterSingle_01", "assets/png/Booster/time skip.png"],
        ["MaintenanceTools_08", "assets/png/Maintainance tool/tool 1.png"],
        ["MaintenanceTools_09", "assets/png/Maintainance tool/tool 2.png"],
        ["MaintenanceTools_10", "assets/png/Maintainance tool/tool 3.png"],
        ["MaintenanceTools_11", "assets/png/Maintainance tool/tool 4.png"], 
        ["Toolbox_03", "assets/png/Toolbox/box 1.png"],
        ["Toolbox_07", "assets/png/Toolbox/box 2.png"],
        ["Toolbox_09", "assets/png/Toolbox/box 3.png"],
        ["Toolbox_05", "assets/png/Toolbox/box 4.png"],
        ["ToyCar_05", "assets/png/Toy car/car 1.png"],
        ["ToyCar_07", "assets/png/Toy car/car 2.png"],
        ["ToyCar_10", "assets/png/Toy car/car 3.png"],
        ["ToyCar_06", "assets/png/Toy car/car 4.png"],
        ["PlantedBush_08", "assets/png/Planted Bush/bush 1.png"],
        ["PlantedBush_09", "assets/png/Planted Bush/bush 2.png"],
        ["PlantedBush_07", "assets/png/Planted Bush/bush 3.png"],
        ["PlantedBush_05", "assets/png/Planted Bush/bush 4.png"],
        ["Energy_02", "assets/png/Energy/energy 1.png"],
        ["Energy_05", "assets/png/Energy/energy 2.png"],
        ["Workbench_05", "assets/png/Workbench/workbench 1.png"],
        ["Workbench_07", "assets/png/Workbench/workbench 2.png"],
      ])
      const computedURL = new URL(assetMap.get(itemType)! || "assets/not-found.png", import.meta.url).href
    return 'url(' + computedURL + ')'
}